class DataUtility:
    def __init__(self):
        self.team_name_list = [
            "ב. ירושלים",
            "מ. אשדוד",
            "ה. ב. שבע",
            "ב. סכנין",
            "מ. חיפה",
            "ה. ירושלים",
            "ה. פ. תקווה",
            "ה. חיפה",
            "ה. ת. אביב",
            "מ. פ. תקווה",
            "מ. ת. אביב",
            "מ. ב. ריינה",
            "מ. נתניה",
            "ה. חדרה",
        ]
        self.full_team_name_list = [
            "מכבי פתח תקווה",
            "הפועל חיפה",
            "מכבי נתניה",
            "הפועל ירושלים",
            "בני סכנין",
            "מכבי חיפה",
            "מכבי בני ריינה",
            "מכבי תל אביב",
            'בית"ר ירושלים',
            "מ.ס. אשדוד",
            "הפועל חדרה",
            "הפועל תל אביב",
            "הפועל פתח תקווה",
            "הפועל באר שבע",
        ]
        self.stats_hebrew_english = {
            "בישולים": "Assists",
            "פנדלים שגרם": "Penalties Caused",
            "לא ספג שערים": "Clean Sheets",
            "פנדלים שנסחטו": "Penalties Squeezed",
            "שערים": "Goals Scored",
            "שערים שספג": "Goals Conceded",
            "דקות משחק": "Minutes Played",
            "הרכב פותח": "Starting Lineup",
            "שערים עצמיים": "Own Goals",
            "פנדלים שהחמיץ": "Penalties Missed",
            "פנדלים שנעצרו": "Penalties Stopped",
            "כרטיסים אדומים": "Red Cards",
            "נכנס בחילוף": "Substituted In",
            "יצא בחילוף": "Substituted Out",
            "כרטיסים צהובים": "Yellow Cards",
        }
        self.position_mapping = {
            "שוער": "GK",
            "מגן/בלם": "CB",
            "קשר": "MD",
            "חלוץ": "FW",
        }
        self.events_list = [
            "Minutes Played",
            "Assists",
            "Penalties Caused",
            "Clean Sheets",
            "Penalties Squeezed",
            "Goals Scored",
            "Goals Conceded",
            "Starting Lineup",
            "Own Goals",
            "Penalties Missed",
            "Penalties Stopped",
            "Red Cards",
            "Substituted In",
            "Substituted Out",
            "Yellow Cards",
        ]
        self.fixture_list = ["All", "Fixture1", "Fixture2"]
        self.fixtures_table = {
            "fixture1": [
                ("מכבי חיפה", "הפועל פתח תקווה"),
                ("מכבי תל אביב", "מ.ס אשדוד"),
                ("הפועל באר שבע", "הפועל חדרה"),
                ('בית"ר ירושלים', "הפועל חיפה"),
                ("בני סכנין", "הפועל תל אביב"),
                ("מכבי פתח תקווה", "הפועל ירושלים"),
                ("מכבי נתניה", "בני ריינה"),
            ],
            "fixture2": [
                ("הפועל חיפה", "מכבי פתח תקווה"),
                ("מ.ס אשדוד", 'בית"ר ירושלים'),
                ("הפועל חדרה", "מכבי תל אביב"),
                ("מכבי בני ריינה", "הפועל באר שבע"),
                ("הפועל תל אביב", "מכבי נתניה"),
                ("הפועל פתח תקווה", "בני סכנין"),
                ("הפועל ירושלים", "מכבי חיפה"),
            ],
            "fixture3": [
                ("מכבי פתח תקווה", "מכבי חיפה"),
                ("בני סכנין", "הפועל ירושלים"),
                ("מכבי נתניה", "הפועל פתח תקווה"),
                ("הפועל באר שבע", "הפועל תל אביב"),
                ("מכבי תל אביב", "מכבי בני ריינה"),
                ('בית"ר ירושלים', "הפועל חדרה"),
                ("הפועל חיפה", "מ.ס אשדוד"),
            ],
            "fixture4": [
                ("מ.ס אשדוד", "מכבי פתח תקווה"),
                ("הפועל חדרה", "הפועל חיפה"),
                ("מכבי בני ריינה", 'בית"ר ירושלים'),
                ("הפועל תל אביב", "מכבי תל אביב"),
                ("הפועל פתח תקווה", "הפועל באר שבע"),
                ("הפועל ירושלים", "מכבי נתניה"),
                ("מכבי חיפה", "בני סכנין"),
            ],
            "fixture5": [
                ("מכבי פתח תקווה", "בני סכנין"),
                ("מכבי נתניה", "מכבי חיפה"),
                ("הפועל באר שבע", "הפועל ירושלים"),
                ("מכבי תל אביב", "הפועל פתח תקווה"),
                ('בית"ר ירושלים', "הפועל תל אביב"),
                ("הפועל חיפה", "בני ריינה"),
                ("מ.ס אשדוד", "הפועל חדרה"),
            ],
            "fixture6": [
                ("הפועל חדרה", "מכבי פתח תקווה"),
                ("בני ריינה", "מ.ס אשדוד"),
                ("הפועל תל אביב", "הפועל חיפה"),
                ("הפועל פתח תקווה", 'בית"ר ירושלים'),
                ("הפועל ירושלים", "מכבי תל אביב"),
                ("מכבי חיפה", "הפועל באר שבע"),
                ("בני סכנין", "מכבי נתניה"),
            ],
            "fixture7": [
                ("מכבי פתח תקווה", "מכבי נתניה"),
                ("הפועל באר שבע", "בני סכנין"),
                ("מכבי תל אביב", "מכבי חיפה"),
                ('בית"ר ירושלים', "הפועל ירושלים"),
                ("הפועל חיפה", "הפועל פתח תקווה"),
                ("מ.ס. אשדוד", "הפועל תל אביב"),
                ("הפועל חדרה", "בני ריינה"),
            ],
            "fixture8": [
                ("בני ריינה", "מכבי פתח תקווה"),
                ("הפועל תל אביב", "הפועל חדרה"),
                ("הפועל פתח תקווה", "מ.ס. אשדוד"),
                ("הפועל ירושלים", "הפועל חיפה"),
                ("מכבי חיפה", 'בית"ר ירושלים'),
                ("בני סכנין", "מכבי תל אביב"),
                ("מכבי נתניה", "הפועל באר שבע"),
            ],
            "fixture9": [
                ("מכבי פתח תקווה", "הפועל באר שבע"),
                ("מכבי תל אביב", "מכבי נתניה"),
                ('בית"ר ירושלים', "בני סכנין"),
                ("הפועל חיפה", "מכבי חיפה"),
                ("מ.ס. אשדוד", "הפועל ירושלים"),
                ("הפועל חדרה", "הפועל פתח תקווה"),
                ("בני ריינה", "הפועל תל אביב"),
            ],
            "fixture10": [
                ("הפועל תל אביב", "מכבי פתח תקווה"),
                ("הפועל פתח תקווה", "בני ריינה"),
                ("הפועל ירושלים", "הפועל חדרה"),
                ("מכבי חיפה", "מ.ס. אשדוד"),
                ("בני סכנין", "הפועל חיפה"),
                ("מכבי נתניה", 'בית"ר ירושלים'),
                ("הפועל באר שבע", "מכבי תל אביב"),
            ],
            "fixture11": [
                ("מכבי פתח תקווה", "מכבי תל אביב"),
                ('בית"ר ירושלים', "הפועל באר שבע"),
                ("הפועל חיפה", "מכבי נתניה"),
                ("מ.ס. אשדוד", "בני סכנין"),
                ("הפועל חדרה", "מכבי חיפה"),
                ("מכבי ריינה", "הפועל ירושלים"),
                ("הפועל תל אביב", "הפועל פתח תקווה"),
            ],
            "fixture12": [
                ("מכבי פתח תקווה", "הפועל פתח תקווה"),
                ("הפועל ירושלים", "הפועל תל אביב"),
                ("מכבי חיפה", "בני ריינה"),
                ("בני סכנין", "הפועל חדרה"),
                ("מכבי נתניה", "מ.ס אשדוד"),
                ("הפועל באר שבע", "הפועל חיפה"),
                ("מכבי תל אביב", 'בית"ר ירושלים'),
            ],
            "fixture13": [
                ('בית"ר ירושלים', "מכבי פתח תקווה"),
                ("הפועל חיפה", "מכבי תל אביב"),
                ("מ.ס אשדוד", "הפועל באר שבע"),
                ("הפועל חדרה", "מכבי נתניה"),
                ("בני ריינה", "בני סכנין"),
                ("הפועל תל אביב", "מכבי  חיפה"),
                ("הפועל פתח תקווה", "הפועל ירושלים"),
            ],
        }
        self.cl_teams_translator = {
            "ברצלונה": "FC Barcelona",
            "קופנהאגן": "F.C. Copenhagen",
            "אוניון ברלין": "1. FC Union Berlin",
            "אנטוורפן": "Royal Antwerp FC",
            "פ.ס.וו איינדהובן": "PSV Eindhoven",
            "מילאן": "AC Milan",
            "פיינורד": "Feyenoord",
            "ריאל סוסיאדד": "Real Sociedad",
            "לייפציג": "RB Leipzig",
            "הכוכב האדום": "FK Crvena zvezda",
            "יאנג בויז": "BSC Young Boys",
            "זלצבורג": "FC Salzburg",
            "לאנס": "RC Lens",
            "בורוסיה דורטמונד": "Borussia Dortmund",
            "סביליה": "Sevilla FC",
            "בנפיקה": "SL Benfica",
            "אתלטיקו מדריד": "Club Atlético de Madrid",
            "אינטר": "FC Internazionale Milano",
            "נאפולי": "SSC Napoli",
            "בראגה": "SC Braga",
            "ארסנל": "Arsenal FC",
            "מנצ`סטר סיטי": "Manchester City",
            "מנצ`סטר יונייטד": "Manchester United",
            "שחטאר דונייצק": "FC Shakhtar Donetsk",
            "גלאטסראיי": "Galatasaray A.Ş.",
            "באיירן מינכן": "FC Bayern München",
            "סלטיק": "Celtic FC",
            "לאציו": "S.S. Lazio",
            "ניוקאסל": "Newcastle United FC",
            "ריאל מדריד": "Real Madrid CF",
            "פורטו": "FC Porto",
            "פ.ס.ז`": "Paris Saint-Germain",
        }
        self.cl_teams_translator2 = {
            "FC Barcelona": "ברצלונה",
            "F.C. Copenhagen": "קופנהאגן",
            "1. FC Union Berlin": "אוניון ברלין",
            "Royal Antwerp FC": "אנטוורפן",
            "PSV Eindhoven": "פ.ס.וו איינדהובן",
            "AC Milan": "מילאן",
            "Feyenoord": "פיינורד",
            "Real Sociedad": "ריאל סוסיאדד",
            "RB Leipzig": "לייפציג",
            "FK Crvena zvezda": "הכוכב האדום",
            "BSC Young Boys": "יאנג בויז",
            "FC Salzburg": "זלצבורג",
            "RC Lens": "לאנס",
            "Borussia Dortmund": "בורוסיה דורטמונד",
            "Sevilla FC": "סביליה",
            "SL Benfica": "בנפיקה",
            "Club Atlético de Madrid": "אתלטיקו מדריד",
            "FC Internazionale Milano": "אינטר",
            "SSC Napoli": "נאפולי",
            "SC Braga": "בראגה",
            "Arsenal FC": "ארסנל",
            "Manchester City": "מנצ`סטר סיטי",
            "Manchester United": "מנצ`סטר יונייטד",
            "FC Shakhtar Donetsk": "שחטאר דונייצק",
            "Galatasaray A.Ş.": "גלאטסראיי",
            "FC Bayern München": "באיירן מינכן",
            "Celtic FC": "סלטיק",
            "S.S. Lazio": "לאציו",
            "Newcastle United FC": "ניוקאסל",
            "Real Madrid CF": "ריאל מדריד",
            "FC Porto": "פורטו",
            "Paris Saint-Germain": "פ.ס.ז`",
        }
        self.event_weights = {
            "Minutes Played": 0.2,
            "Assists": 3,
            "Penalties Caused": -4,
            "Clean Sheets": 4,
            "Penalties Squeezed": 2,
            "Goals Scored": 5.4,
            "Goals Conceded": -2,
            "Starting Lineup": 3,
            "Own Goals": -5,
            "Penalties Missed": -4,
            "Penalties Stopped": 4,
            "Red Cards": -3,
            "Substituted In": 0.5,
            "Substituted Out": -0.5,
            "Yellow Cards": -1,
        }

    # def set_team_attributes(self, team_dict):
    #     for team_name in team_dict.keys():
    #         print(f"Enter attributes for team: {team_name}")
    #         overall = float(input("Overall rating: "))
    #         attack = float(input("Attack rating: "))
    #         defend = float(input("Defend rating: "))

    #         # Update the team attributes in the dictionary
    #         team_dict[team_name]["overall"] = overall
    #         team_dict[team_name]["attack"] = attack
    #         team_dict[team_name]["defend"] = defend

    #     return team_dict


# dt = DataUtility()

# team_dict = {
#     team_name: {"overall": 0, "attack": 0, "defend": 0}
#     for team_name in dt.full_team_name_list
# }
# team_dict = dt.set_team_attributes(team_dict)
# print(team_dict)
